### ISSUE TITLE
Delete engines node >= 10 and update to 12

### ISSUE THREAD

**Issue by ciricc** [sindresorhus/got#1086]
I tried run got on NodeJS 10.16 and this not worked for me.

Need set node support from 10 to 12, because on 10 you can see this error in any request

`GotError: Cannot read property 'startsWith' of undefined`

**Comment by szmarczak** [comment]
This is a Node.js issue (happens for all HTTP clients), not a Got one.

**Comment by gregory** [comment]
@szmarczak while you are right about the fact of this being a node issue, this package.json tells the lib is compatible with node >=10, which is not true, because of the Node.js issue.

**Comment by szmarczak** [comment]
It is Node.js 10-compatible, but in some cases it just won't work because the internal Node.js `urlToOptions` module is broken.

**Comment by gregory** [comment]
can we at least make a note in the readme about the features that are broken with node 10? I'm stuck in Node 10 for some other reason and upgrading got broke a lot of stuff. If I didn't have automated test I wouldn't have known. 
IMO a note in the readme or an constraint on the node version in the package.json would have helped. 
Also, what do you think about maybe using query-string instead of URLSearchParams ?

**Comment by szmarczak** [comment]
no
