### ISSUE TITLE
ENOTFOUND on got.post with docker cluster expose name

### ISSUE THREAD

**Issue by abaetu** [sindresorhus/got#1183]
Hello,
got@10 works fine. got@11 fails to fetch a web page using the cluster expose name of a docker http service: ENOTFOUND.

**Comment by abaetu** [comment]
what is invalid?

**Comment by szmarczak** [comment]
You did not fill out the template

**Comment by abaetu** [comment]
I didn't have time to fill out the template, since i lost a couple of hours at work debugging. Looks like someone else did that and you replied 2 days ago. So it is fresh for you. You should have replied: "we know about this bug, working on it" 
https://github.com/sindresorhus/got/issues/1175

**Comment by szmarczak** [comment]
Your issue is not precise, I had no idea you were talking about short hostnames. By the content of your issue it could even be an entry in the `hosts` file and the CacheableLookup instance failed to read that.

> I didn't have time to fill out the template

Nonsense. Everybody has got the time to do so. I'm sure it wouldn't take you more than two minutes.

> Looks like someone else did that and you replied 2 days ago.

![image](https://user-images.githubusercontent.com/36894700/80278452-9bab6800-86f6-11ea-906c-fd29cf68c825.png)

It's fourth element on the list. You surely saw this and still decided to open an issue anyway. 

> You should have replied: "we know about this bug, working on it"

See the first paragraph. You should've replied there first.

**Comment by szmarczak** [comment]
I'm not the author of this issue, so it's your responsibility to provide as much information as possible.
