### ISSUE TITLE
Suggestion: rename `pagination()` to `pagination.each()`

### ISSUE THREAD

**Issue by fiznool** [sindresorhus/got#1195]
#### What problem are you trying to solve?

Clear up any misunderstanding in the pagination API, specifically the difference between `pagination` and `pagination.all`.

#### Describe the feature

Remaning `pagination` to `pagination.each`. The two methods will then reflect their mode of operation:

 - `.all`: fetches all results from the API, recursively paginating if necessary. Returns a promise which resolves to the full list of results.
- `.each`: returns an async iterator, which allows you to iterate over the results using `for await` syntax. Similar in concept to streaming, used when you expect more results than can feasibly fit in memory at once.

Note this is simply a proposal to change nomenclature - the actual features remain the same.

Related discussion: https://github.com/sindresorhus/got/issues/1052#issuecomment-619409472

#### Checklist

- [x] I have read the documentation and made sure this feature doesn't already exist.

**Comment by szmarczak** [comment]
@PopGoesTheWza I see you've downvoted this issue. It would be awesome if you could explain your thinking. I'm not saying that you're not right, we just need your thoughts on this :smiley:

Initially this doesn't have to be a breaking feature. It can be this:

```js
// The same:
got.pagination(...)
got.pagination.each(...)

// All (unchanged):
got.pagination.all(...)
```

**Comment by PopGoesTheWza** [comment]
My reasoning:

1. I don't like the method name `.each()` (but that is of little relevance)
1. adding an aliased `.paginate.each()` which is exactly the same as `.paginate()` sounds clumsy/kludgy to me
1. expanding documentation with more detailed description and examples would be more useful

Now with more than one way to work with `pagination`, I would rather change the method naming like this:

- Keep `.paginate()` and `.paginate.all()` for compatibility (possibly deprecated)
- Use first level methods with fully descriptive name (i.e. `.paginateEach()`/`.paginateIterator()` and `.paginateAll()`) This approach should leave the introduction of new method clearer/easier (i.e. if there is need for a method which iterates each page while returning every items from current page, add a `.paginatePaged()` method)

**Comment by szmarczak** [comment]
1. It can be `.iterator()`.
2. This is required to avoid breaking changes if we want to add `paginate.each()`.
3. I agree 100%.

- :+1:
- > Use first level methods with fully descriptive name
  
  `got.paginateIterator()` is buttery butter - two verbs meaning the same. No need to mention the same thing twice. `got.paginationIterator()` seems to be a bit better. So it's either `got.iterator()` or `got.paginate()`. But then we are where we started at. But currently it's `got.paginate()`, so if we want `.all()`  then it's either `got.paginateAll()` or `got.paginate.all()`. And we're at the beginning of this issue. **Madness.** I'm getting crazy :P
  
  Renaming `all()` to `getAll()` is an option too.

  That's why I personally prefer `got.paginate.each()`. Alternatively we can go with `got.iterator()`. Then it needs to be `got.iterator.getAll()`.

I cannot decide. It's complete madness for me.

@sindresorhus What are your thoughts on this?

**Comment by sindresorhus** [comment]
I don't really see the strong need to rename, but I'm fine with `.pagination.each()` and `.pagination.all()`.
