### ISSUE TITLE
Responses are not cached on Node.js ≥ v14.0.0

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/got#1216]
```
  5 tests failed
  2 known failures
  1 test skipped

  arguments.ts › throws an error when legacy URL is passed
  pagination.ts › pagiantion using searchParams

  cache.ts › cacheable responses are cached


  Difference:

  - 0
  + 1

  › dist/test/cache.js:31:7
  › dist/test/helpers/with-server.js:38:9



  cache.ts › cached response is re-encoded to current encoding option


  Difference:

  - 0
  + 1

  › dist/test/cache.js:42:7
  › dist/test/helpers/with-server.js:38:9



  cache.ts › redirects are cached and re-used internally


  Difference:

  - 2
  + 3

  › dist/test/cache.js:72:7
  › dist/test/helpers/with-server.js:38:9



  cache.ts › can replace the instance's HTTP cache


  Difference:

  - 0
  + 1

  › dist/test/cache.js:215:7
  › dist/test/helpers/with-server.js:38:9



  cache.ts › `isFromCache` stream property is true if the response was cached


  Difference:

  - false
  + true

  › dist/test/cache.js:148:7
  › runMicrotasks (<anonymous>)
  › dist/test/helpers/with-server.js:38:9
```

**Comment by Giotino** [comment]
The bug is caused by https://github.com/sindresorhus/got/blob/812deb690bc67b9bb2a0a28f10ece46c7905c78c/source/core/index.ts#L1477

When it's called it emit an "abort" event on the request, if `cacheable-request` detect an "abort" (or "error") event it mark the request as failed and thus it's not added to the cache.

Code references:
https://github.com/lukechilds/cacheable-request/blob/master/src/index.js#L75,L80
https://github.com/lukechilds/cacheable-request/blob/master/src/index.js#L113,L115
https://github.com/lukechilds/cacheable-request/blob/master/src/index.js#L154,L155

Also it seems that [request.abort](https://nodejs.org/api/http.html#http_request_abort) has been deprecated since v14.1.0 with the suggestion to use [request.destroy](https://nodejs.org/api/http.html#http_request_destroy_error)

Reading the Node.JS documentation the 2 functions do the same things if no arguments are specified (I haven't investigated about possible sides effects. You know... Node.JS tends to be unpredictable)

**Comment by Giotino** [comment]
I ran a full test changing only that line.

```
2 tests failed
4 known failures
1 test skipped

pagination.ts » allowGetBody sends correct json payload with .paginate()
pagination.ts » `hooks` are not duplicated
pagination.ts » pagination using searchParams
arguments.ts » throws an error when legacy URL is passed
```

**Comment by szmarczak** [comment]
Great! Feel free to send a PR. I'll look into this tomorrow.

**Comment by Giotino** [comment]
There are things that I want to look into before sending a PR.

For example:
According to the Node.JS documentation the event "abort" can only be emitted by request.abort(). request.abort is deprecated, but the "abort" event is not...

**Comment by Giotino** [comment]
While reviewing the changes i found out that there will be a change in a repo of yours, used by Got.

https://github.com/szmarczak/http-timer have a timer on the "abort" event (that isn't officially deprecated yet, but it can't be emitted).

Should it be renamed to close and look for the "close" event?

The "close" event is related to the [stream.Writable](https://nodejs.org/api/stream.html#stream_class_stream_writable) class. It's emitted when all the resources of the stream have been closed.

Looking at the usage in Got I can say that "abort" was used the same way, when the request was destroyed.
So I suggest to use the "close" event for the timer and, maybe, to not change the API leaving the name of the property "abort".
