### ISSUE TITLE
Set Min/MAX TLS version and ciphers for requests

### ISSUE THREAD

**Issue by seiya-git** [sindresorhus/got#1299]
#### What would you like to discuss?

How to set Min/MAX TLS version and ciphers for requests?

#### Checklist

- [x] I have read the documentation.

**Comment by Giotino** [comment]
Currently there's no official/documented way to do that (we could make a new PR like #1255).

An undocumented way could be to use `minVersion` and `maxVersion` into the options. I don't know if it's going to work because, as you can see below, it's not present in the Node.JS documentation.

@szmarczak
In PR #1255 I implemeted the most used HTTPS options, but there were more:
> The following additional options from tls.connect() are also accepted: ca, cert, ciphers, clientCertEngine, crl, dhparam, ecdhCurve, honorCipherOrder, key, passphrase, pfx, rejectUnauthorized, secureOptions, secureProtocol, servername, sessionIdContext, highWaterMark.

I can make a new PR with the remaining options.

I think all the [`tls.createSecureContext`](https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options) options could work even if undocumented.

**Comment by szmarczak** [comment]
There are Node.js command line options for that and those should suffice your needs.
