### ISSUE TITLE
ts-node: error TS2339: Property 'body' does not exist on type 'CancelableRequest<Response<string>>'

### ISSUE THREAD

**Issue by akopchinskiy** [sindresorhus/got#1401]
#### Describe the bug

 - Node.js version: 14.7.0
 - OS & version: Win 10
 - got: 11.5.2

#### Actual behavior

```ts
// error TS2339: Property 'body' does not exist on type 'CancelableRequest<Response<string>>'.

const { body } = await got.get(this.url);
```

#### Expected behavior

no errors

#### Code to reproduce

```ts
// main.ts
const { body } = await got.get('https://google.com/');
```

Then:
`ts-node ./main.ts`

#### Checklist

- [X] I have read the documentation.
- [X] I have tried my code with the latest version of Node.js and Got.

**Comment by Giotino** [comment]
I know this issue is a more than a month old.

I cannot reproduce it, can you test it with the latest Got and Typescript, thanks.

**Comment by tobiasmuehl** [comment]
Had the same issue because I had an old version of got installed in a folder that is a parent of the folder (even there there was a local node_modules)

Imagine `~/node_modules` containing got 9, `~/new-project/node_modules` containing got 11 and ts-node gets confused about the new-project. `tsc` still worked as expected.
