### ISSUE TITLE
Replacing body/form/json in beforeRequest hook does not function properly

### ISSUE THREAD

**Issue by zedd3v** [sindresorhus/got#1427]
Editing options.body inside the beforeRequest hook does not affect it.

 - Node.js version: v14.4.0
 - OS & version: Windows 10

#### Actual behavior
```js
options.body = "body";
// => ""
```

#### Expected behavior
```js
options.body = "body";
// => "body"
```

#### Code to reproduce
```js
const test = got.extend({
    hooks: {
        beforeRequest: [
            (options) => {
                options.body = "test"
            },
        ],
    },
});
const { body } = await test('https://httpbin.org/anything');
```
Try it out: https://github.com/zedd3v/got-issue

- [✓ ] I have read the documentation.
- [✓ ] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Can you please fill out the template properly? Thanks.

**Comment by zedd3v** [comment]
> Can you please fill out the template properly? Thanks.
Done. Sorry for the initial post

**Comment by Giotino** [comment]
The problem is that the body is written to the request is `this[kBody]` (https://github.com/sindresorhus/got/blob/master/source/core/index.ts#L2194) which is created by `finalizeBody()` (https://github.com/sindresorhus/got/blob/master/source/core/index.ts#L1863).
If the body should be replaceable with `beforeRequest` Got should check, right after applying the beforeRequest hooks, if the body is changed and, if yes, change `this[kBody]` accordingly.

**Comment by Giotino** [comment]
BTW @zedd3v It seems that httpbin.org does not accept body for GET requests, so even if the body had been replaced your example wouldn't have worked.

You should use something like a POST request:
```
const test = got.extend({
    method: 'POST',
    hooks: {
        beforeRequest: [
            (options) => {
                options.body = "test"
            },
        ],
    },
});
const { body } = await test('https://httpbin.org/anything');
```
