### ISSUE TITLE
I can return a promise from a handler if the request requests a Stream?

### ISSUE THREAD

**Issue by ashuradev** [sindresorhus/got#1480]
#### What would you like to discuss?

Hello, I need to throttle requests that is sent to Got, I'm using the library p-throttle to this. This library returns a promise when try to execute the throttled function. My current code is:

```js
const pThrottle = require('p-throttle');

const throttle = (concurrentlyRequests, requestInterval) => {
  const throttled = pThrottle(
    (options, next) => next(options),
    concurrentlyRequests,
    requestInterval * 1000
  );

  return (options, next) => {
    // I can remove this for throttle stream requests?  
    if (options.isStream) {
      return next(options);
    }

    return throttled(options, next);
  };
};

const got = got.extend({
  handlers: [throttle(2, 5)]
});
```

I am in doubt if I can return a Promise even if the request requests a stream, because from what I read in the documentation the recommended thing is to ignore the streams when the handler is asynchronous. What would be the implications of this?

#### Checklist

- [x] I have read the documentation.

**Comment by sindresorhus** [comment]
I think a `beforeRequest` hook would be a better fit for your needs: https://github.com/sindresorhus/got#hooksbeforerequest

**Comment by ashuradev** [comment]
Would you have an example of this?

**Comment by szmarczak** [comment]
No, you cannot remove `next(options)` as the result is returned when you call `got.stream()`. You could return a Promise though but then you'd have to `await got.stream()` every call, which looks a bit ugly (and TypeScript will throw).

It would be best if the function that calls `got.stream()` was throttled instead. Something like:

```js
const think = () => new Promise((resolve, reject) => {
    const stream = got.stream(options);
    // Process the stream
    
    stream.once('error', reject);
    stream.once('end', resolve);
});

const throttled = throttle(think, ...);
```

As @sindresorhus has already mentioned, you could delay the requests via a `beforeRequest` hook (or throw to cancel), since it can be async. For example call there a throttled `Promise.resolve()`.
