### ISSUE TITLE
Hacktoberfest?

### ISSUE THREAD

**Issue by Giotino** [sindresorhus/got#1485]
Hacktoberfest has became opt-in (https://hacktoberfest.digitalocean.com/hacktoberfest-update), should Got participate?

It's true that we can face a lot of spam, but I think this could be a good opportunity to have some small, well welcomed, PRs (eg. improving the documentation, fixing small bugs that nobody wants to address) and gain interest on this repo.

@sindresorhus @szmarczak

**Comment by szmarczak** [comment]
I don't think there important issues that beginners could do.

**Comment by Giotino** [comment]
So the "good for beginner" label is a lie?

**Comment by szmarczak** [comment]
You got me wrong. I just said the current ones aren't that important.

**Comment by sindresorhus** [comment]
Nah. I did it some years ago when it was also opt-in and I only got really low-quality PRs (and I spent a lot of time on reviews and never get a response), and it was just a waste of time in the end. The incentive is all wrong. People contribute to get something instead of doing it to actually get involved and improve their skills.
