### ISSUE TITLE
Any chance duplexer2 could be published as not a scoped dependency?

### ISSUE THREAD

**Issue by tolmasky** [sindresorhus/got#151]
Unfortunately npm has not made scoped packages available (to replication) since this: http://status.npmjs.org/incidents/6r2jr0dd9kd5 . At some point they should be again, but until then we can't provide them on tonicdev.com. As such, currently require("got") breaks on tonicdev, which is bad since its the go to library we suggest for http requests. Could you possibly just publish it with a different name, like duplexer2-got or something (I know it sucks, just no real way around this).

**Comment by sindresorhus** [comment]
Sure.

@floatdrop Can you publish it as `duplexer3` (makes sense since it's now using Streams 3).

-

// @bcoe @othiym23 Just fyi. Would be nice if the docs for scoped public packages mentioned all the known issues so people would know not to use them. Currently as far as I know: They don't work for replication, they don't show up in search, they don't have stats, they fail on older Node.js versions, and some more issues I can't remember right now.

**Comment by floatdrop** [comment]
Done. Published as `6.0.1`.
