### ISSUE TITLE
requests hang

### ISSUE THREAD

**Issue by yuriscom** [sindresorhus/got#1547]
#### Describe the bug
There are urls that it fails to get. I am unable to get response from www.thesun.co.uk for example. Just hangs with no error or any response whatsoever. 
Axios and Request npms are able to get the response. 

 - Node.js version: 10.23 
 - OS & version: MacOS
- Got version 11.8.0

#### Actual behavior

```
const requestGot = require('got');
await requestGot('https://www.thesun.co.uk/money/')
console.log("got the result")
```

"got the result" line never reaches;

#### Expected behavior

const request = require('request');

    request('https://www.thesun.co.uk/money/', { json: true }, (err, res, body) => {
       console.log("got the result")
    });

Works fine

await axios.get('https://www.thesun.co.uk/money/');

Works fine too

**Comment by szmarczak** [comment]
What's your Got version?

**Comment by yuriscom** [comment]
got version 11.8.0

**Comment by Giotino** [comment]
`www.thesun.co.uk` use Akamai CDN, they denied the access to the website to "uncommon" User Agents (like the one that Got advertise), a fix for your problem is to change the user agent, like this:

```js
const got = require('got');

(async () => {
  await got('https://www.thesun.co.uk/money/', {
      headers: {
      "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36"
    } 
  });

  console.log('got the result');
})();
```

!BUT!

When using CURL, on the same website, using an "uncommon" user agent it reply (with an "Access Denied" page, but it replies). So Got has some problem with that kind of response.

**Comment by Giotino** [comment]
Update: I was experiencing different behavior with Got and CURL because CURL defaults to HTTP/2, while Got uses HTTP/1.1

When using HTTP/2 on Got i receive the 403 Forbidden response (which I was receiving with CURL), when i use HTTP/1.1 on CURL it hangs, like Got.

So this issue is entirely due to to Akamai and their "filter" that drops the connection (without closing it) and leave the client hanging.
