### ISSUE TITLE
Package includes @types as dependencies instead of peerDependencies

### ISSUE THREAD

**Issue by DanielOrtel** [sindresorhus/got#1620]
#### Describe the bug
 - Node.js version: N/A
 - OS & version: N/A

It is a common scenario to remove @types from production builds, however this module includes [two of them](https://github.com/sindresorhus/got/blob/main/package.json#L48) as package dependencies which makes it really hard to do. We're not even directly dependent on this project, so we can't do much about it, except not remove types from the prod build of our app or hack around it. 

#### Actual behavior
`@types` packages are installed as dependencies

#### Expected behavior
`@types` packages are listed as peer dependencies 

#### Code to reproduce
N/A, but [here's a link](https://github.com/sindresorhus/got/blob/main/package.json#L48) to the package.json lines
#### Checklist

- [N/A] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
AFAIK, adding types you use as dependencies is common practice. Up until recently, things in `peerDependencies` did not automatically install, which would make Got fail to run in TypeScript after running `npm i got`, which is not a good experience.  Even though newer npm versions install peer dependencies automatically, we cannot assume what npm version people are on. Even then, I think it's more correct to have them in `dependencies` as they actually are dependencies.

**Comment by DanielOrtel** [comment]
yes, the point of peerDependencies is that they don't install automatically, but require consumers to install them. That was my whole point, it shouldn't install automatically. 

Since typescript is a build-time process, not a runtime process, it is as a development dependency. Of the literally thousands of packages we have installed locally, only 3 have `@types` listed as a direct dependency, so I also wouldn't say it's a common practice.

**Comment by sindresorhus** [comment]
> That was my whole point, it shouldn't install automatically.

npm 7 installs them automatically, so that's not going to work for you in the future.

> Of the literally thousands of packages we have installed locally, only 3 have @types listed as a direct dependency, so I also wouldn't say it's a common practice.

It is. It's just that most packages ship with type definitions in the package itself.

**Comment by DanielOrtel** [comment]
> npm 7 installs them automatically, so that's not going to work for you in the future.

`npm install --only=production` or `yarn install --production` will not though. And this is where we want to prevent auto-install of @types dependencies.  Not when using local development install, obviously we'd need the types there. 

> It is. It's just that most packages ship with type definitions in the package itself.

But they do rely on external types. My point is they either use them as devDependencies or peerDependencies.

**Comment by cesarfd** [comment]
Hi. Yes, all the `@types/*` should be moved to `devDependencies`. They do nothing on production envs and of all the repos I maintain got is the only one with types in `dependencies`.

It doesn't make much sense and they bring other subdependencies too (with `npm ls -prod`):

```
└─┬ got@11.8.2
  ├─┬ @types/cacheable-request@6.0.1
  │ ├─┬ @types/keyv@3.1.1
  │ │ └── @types/node@14.14.37  deduped
  │ └── @types/node@14.14.37
  └─┬ @types/responselike@1.0.0
    └── @types/node@14.14.37  deduped
```

```
└─┬ got@11.8.2
  └─┬ @types/cacheable-request@6.0.1
    └── @types/http-cache-semantics@4.0.0
```

**Comment by szmarczak** [comment]
> They do nothing on production envs

If you're using TypeScript, then builds will fails.

**Comment by cesarfd** [comment]
> If you're using TypeScript, then builds will fail.

Maybe I'm missing something here, but during builds both dependencies and devDependencies are installed, it's a regular npm install. Or it's a different problem?

**Comment by szmarczak** [comment]
> during builds both dependencies and devDependencies are installed

No.

**Comment by cesarfd** [comment]
Ok I'm sorry but there's definitely something I don't understand. Why does got have a couple of @types/ packages in its `dependencies` instead of `devDependencies` where they should be? 

What do you mean by just "builds will fail"? Which builds? Modules that depend on got? Got itself? And if so, how? Why?

Why would anyone need a @types/ module outside of the development/building phase? In production I'm using `npm ci --production` so I don't want any package like @types/ installed as they shouldn't be there, they just pollute node_modules. Same reason we don't install jest in dependencies.

**Comment by szmarczak** [comment]
> Why does got have a couple of @types/ packages in its dependencies instead of devDependencies where they should be?

If you're using TypeScript, then builds will fail [if it were devDependencies].

**Comment by cesarfd** [comment]
> If you're using TypeScript, then builds will fail [if it were devDependencies].

Again with the same shit? Are you 12? I'm asking you **_why_** builds will fail and **_which builds_** are you talking about.

**Comment by DanielOrtel** [comment]
> If you're using TypeScript, then builds will fail [if it were devDependencies].

that still doesn't justify defining them as production dependencies. This is why peer dependencies exist to let the consumer know that they need that as well. 

also @cesarfd, not cool, keep it civil. Also, to your question, consumer TS builds would fail if they manually add the types currently listed as production dependencies.

**Comment by cesarfd** [comment]
> also @cesarfd, not cool, keep it civil. Also, to your question, consumer TS builds would fail if they didn't manually add the types currently listed as production dependencies

I'm telling him explicitly that I don't understand why this builds would fail and keeps saying the builds will fail, using the same same sentence. _That_ is disrespectful.

So given that you are civil enough to care about this and be respectful at the same time (thank you): by consumer builds you mean when someone tried to build (compile? dist?) a project with got as a dependency it would fail if these two dependencies are not listed in prod dependencies? But how is that even possible? Either got or some other dependency must have a bug. There's no immediate reason I can think of that suggests a @types/ package should be outside devDependencies.

I mean, the packages will be there if you run an npm install. This is weird.

**Comment by szmarczak** [comment]
> I'm asking you why builds will fail

I already have answered this. If the types are in `devDependencies`, building your TypeScript project will fail because Got doesn't have the required types and TypeScript will throw because they are missing.

> which builds are you talking about.

Building any TypeScript project that requires Got.

> Again with the same shit? Are you 12?

I have answered why the builds will fail. Instead of guessing, you could simply test this on your own.
Please refrain from being toxic. Next time you'll be blocked with no further notice.

After all it doesn't matter if the types are in `dependencies` or `peerDependencies`, see https://github.com/sindresorhus/got/issues/1620#issuecomment-781105179

> yarn install --production will not though

I haven't tested this, but the docs don't mention anything about it at all: https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install-production-true-false

**Comment by szmarczak** [comment]
> I'm telling him explicitly that I don't understand why this builds would fail and keeps saying the builds will fail, using the same sentence.

No, you asked `why builds will fail` and not why `devDependencies` cause a fail.

**Comment by cesarfd** [comment]
> I already have answered this. If the types are in `devDependencies`, building your TypeScript project will fail because Got doesn't have the required types and TypeScript will throw because they are missing.

Well, something must be wrong then, because this module is literally the only one I can think of that needs a @types package as a regular dependency. 

It doesn't matter if got is a TS project itself, it should be published in such a way it doesn't need this as @DanielOrtel is telling you.

**Comment by szmarczak** [comment]
> this module is literally the only one I can think of that needs a @types package as a regular dependency.

Can you attach an example that doesn't have `@types` as regular dependencies?

**Comment by cesarfd** [comment]
> > this module is literally the only one I can think of that needs a @types package as a regular dependency.
> 
> Can you attach an example that doesn't have `@types` as regular dependencies?

Yeah, sure.

The entire @aws-sdk v3 module collection.
Babel and all its dependencies (but it doesn't matter, its always installed as a devDep).
The entire Jest module collection (but it doesn't matter, its always installed as a devDep).
sindresorhus's "is".
http-timer
big-integer
bs-logger
cacheable-lookup
node-config
fastify (and plugins)
ioredis
is-stream
typescript :) (but it doesn't matter, its always installed as a devDep).
...
etc., etc.

**Comment by szmarczak** [comment]
@cesarfd But those packages require only `@types/node` to run in a TypeScript environment. Furthermore, some (e.g. `cacheable-lookup`) use types for testing. So these examples are irrelevant.

Got, in order to run in TypeScript, requires the `@types/cacheable-response` package because it is used **directly** by Got. `cacheable-request` is a Got dependency Moving the types to devDependencies would cause an error. That means we can't do that.

Or... can we? We could make a script that would check what is the environment and would install the types accordingly. But that is a workaround and should be considered only when necessary.

Feel free to make an issue in the TypeScript repo to exclude the `node` types from being installed by default. That way Got would save 600KB+.

I'm going to rewrite the `cacheable-request` package. But first we're releasing Got 12 soon. Note that `cacheable-lookup` doesn't require the Keyv types - it provides [in the types] a general interface, which is only a few lines of code.

I hope this clarifies why we can't move the types to devDependencies.

**Comment by szmarczak** [comment]
https://cdn.jsdelivr.net/npm/@types/keyv@3.1.1/package.json

See the dependencies here. This is shipped by DefinitelyTyped.

**Comment by cesarfd** [comment]
Thanks @szmarczak now I get the idea much better than before. It's just bad luck with this specific set of dependencies. 

Jeez I got stuck thinking this was so simple and it's not.
