### ISSUE TITLE
Retry Mechanism Stopped working after v11.8.2 published

### ISSUE THREAD

**Issue by prabhatmishra33** [sindresorhus/got#1649]
#### Describe the bug

 - Node.js version: 
 - OS & version: 

#### Actual behavior
Retry Was working with version v11.8.1
...

#### Expected behavior
Should perform retry mechanism.
...

#### Code to reproduce
install v11.8.2
```js
...
```

#### Checklist

- [ ] I have read the documentation.
- [ ] I have tried my code with the latest version of Node.js and Got.

**Comment by sindresorhus** [comment]
// @fungiboletus

**Comment by prabhatmishra33** [comment]
This issue is mainly appearing in our production environment.

**Comment by fungiboletus** [comment]
I will investigate the issue. Is the issue in your production environment related to DNS queries and/or kubernetes doing kubernetes things ?

**Comment by fungiboletus** [comment]
I spent some time trying to understand what could go wrong after [the small change between 11.8.1 and 11.8.2](https://github.com/sindresorhus/got/compare/v11.8.1...v11.8.2) but I would need more information. 

Can you reproduce the issue ? I tried to reproduce it but I cannot, all the unit tests are successful including the `retry.ts` ones and I also simulated DNS issues on my computer and got retried successfully as well. I also read the got source code but I don't see any obvious problem with retrying and the `globalDnsCache` initialization.

It could be an update of a dependency, `cacheable-lookup` is set to `^5.0.3` in Got's package.json so you may have the version `5.0.4` installed. You could try to install the previous version to see if it changes anything. `npm install --save --save-exact cacheable-lookup@5.0.3` I took a quick [look at the diff](https://github.com/szmarczak/cacheable-lookup/compare/v5.0.3...v5.0.4) but it seems fine to me.

Is everything else the same in your production environment since you upgraded got ?

**Comment by prabhatmishra33** [comment]
@fungiboletus Thanks for taking this up, One more info I would like to share is, we are also using [ibmmq](https://www.npmjs.com/package/ibmmq)  package which we see has a dependency of got installed: 9.6.0 do you see issue with this?

**Comment by prabhatmishra33** [comment]
Thanks, @fungiboletus for taking devoting your precious time, the issue seems to be from our side in a setting of delayed time.
