### ISSUE TITLE
BUG??

### ISSUE THREAD

**Issue by andress134** [sindresorhus/got#1777]
#### Describe the bug

 - Node.js version: v14.17.2
 - OS & version: debian 9 

#### Actual behavior

...

#### Expected behavior

/root/node_modules/got/dist/source/core/index.js:1346
                    this[kRequest].emit('upload-complete');
TypeError: Cannot read property 'emit' of undefined
#### Code to reproduce

```js
...
```

#### Checklist

- [ ] I have read the documentation.
- [ ] I have tried my code with the latest version of Node.js and Got.

**Comment by phawxby** [comment]
@szmarczak we're having the same issue with V11.8.5 and I think it might be related to usage of msw. I notice the code is different between V11 and V12, is that due to a bug being patched or general refactoring? 

I'd love to move our project over to ESM and upgrade got to see but sadly the trigger on that has been pulled far too early to be feasible for us.

**Comment by szmarczak** [comment]
@phawxby What's the code behind line 1364 (in 11.8.5 it's just a bracket)?
