### ISSUE TITLE
I'm using CommonJS! What should I do?

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/got#1789]
### Please [read this](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

If you can't move to ESM yet, please stay on the Got v11 branch. 

### Workarounds for Got v12

0. Use `await import('got')`.
1. Use a wrapper: https://gist.github.com/szmarczak/0f2b70b2a1ed52a56a6d391ac02d094d
   *Disclaimer: the first request needs to be a Promise.*
2. Use a third party module such as `got-cjs`: https://github.com/apify/got-cjs

**Comment by etnbrd** [comment]
Unfortunately, `got@12.0.0` depends on `p-cancelable@3.0.0`, which [became an ESM only package as well](https://github.com/sindresorhus/p-cancelable/commit/d44ac233341b416840f67ae61b3cd8d19bb52b44), so I doubt these alternative would work anymore. I only briefly tested the second alternative `got-cjs`, though.
Additionally, `got` depends on `node:events`, which only make sense in ESM. But it should probably be easy to remove the `node:` part in the module specifier during the package publication.

**The right direction to go is clearly to move to ESM**.
But in the meantime, if there is enough support, maybe we could try to provide cjs versions of both `got` and `p-cancelable`, and it could buy enough time to migrate to ESM?

**Comment by szmarczak** [comment]
Node v12.22.0 has been released *almost* a year ago (2021-03-30) and it has brought stable support for ESM.
Moving back is very unlikely. Please use `await import('got')` or use `got-cjs`.

**Comment by etnbrd** [comment]
Ah, I didn't know it was possible to use `await import('got')` from CJS to import ESM package. I'll give that a try, thanks 🙇 

Regarding `got-cjs`, latest version is `v12.0.0-beta.4`: https://www.npmjs.com/package/got-cjs?activeTab=versions
Which still uses `p-canceleable@2.1.1` https://github.com/sindresorhus/got/blob/v12.0.0-beta.4/package.json#L57 which is not an ESM package: https://github.com/sindresorhus/p-cancelable/blob/v2.1.1/package.json

I tried to update `got-cjs` with latest `got@12.0.0` but it now depends on `p-cancelable@3.0.0`, which is an ESM package, and it imports `node:events`, which is incompatible with CJS. Because of these, the recompilation of `got@12.0.0` into `got-cjs@12.0.0` doesn't seem to be working with the current github-action. To keep `got-cjs` up-to-date, it seems we would have to recompile `p-cancelable@3.0.0` as well, and update the dependencies to use `p-cancelable-cjs` and `events` instead of `p-cancelable` and `node:events`.

This might be time-consuming, so before trying that route, I just wanted to know if there is support, and if that's something we should consider.

**Comment by szmarczak** [comment]
@etnbrd `got-cjs` downgrades these [deps](https://github.com/apify/got-cjs/blob/0e23b04c8d4956bf2190458489efa1a971876eec/build.mjs#L18-L20) and works flawlessly.

**Comment by sindresorhus** [comment]
Just closing this as it's pinned so it doesn't need to be open.

**Comment by intech** [comment]
Maybe a better solution would be to build both modules using the example https://github.com/mike-marcacci/node-redlock/pull/114
