### ISSUE TITLE
searchParams working differently to qs in request

### ISSUE THREAD

**Issue by moonpie79** [sindresorhus/got#2083]
The following code https://runkit.com/embed/vlup438ox8p5 sets `qs={ filter: { where: { Id: 'abcd' } } }` in `request` and produces a query like `filter[where][Id]=abcd` but when I try to set the same with `searchParams` using got (see code at the end) I get this error 
```
Expected value which is `predicate returns truthy for any value`, received values of types `Object`
```

Am I doing something wrong or is this a bug in got?

Minimal recreate
```
async function main() {
  const { default: got } = await import('got')
  try {
    const response = await got('https://httpbin.org/anything', {
      searchParams: { filter: { where: { Id: 'abcd' } } }
    })
  } catch (error) {
    console.error(error.message)
  }
}

main()
```

**Comment by szmarczak** [comment]
The error is quite cryptic due to https://github.com/sindresorhus/is/issues/107

---

The `searchParams` is passed to [`URLSearchParams`](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) which doesn't support nested parameters.

Please note that query string != search parameters.

If you're the server developer, I encourage you to use POST instead - it's the right approach to do.\
Alternatively you could use dot notation: `{ 'filter.where.Id': 'abcd' }`

If you're forced to use `[]` then you need to use query string instead:

```js
async function main() {
  const { default: got } = await import('got')
  try {
    const response = await got('https://httpbin.org/anything?filter[where][Id]=abcd')
  } catch (error) {
    console.error(error.message)
  }
}

main()
```

Please note that then you must not provide the `searchParams` parameter.

---

Also I noticed that you `await import('got')` every time. Most likely that is a performance hit, you can import Got just once:

```js
const importGot = import('got');

async function main() {
  const { default: got } = await importGot;
  try {
    const response = await got('https://httpbin.org/anything?filter[where][Id]=abcd')
  } catch (error) {
    console.error(error.message)
  }
}

main()
```
