### ISSUE TITLE
Hook `beforeError` does not respect the `throwHttpErrors` setting

### ISSUE THREAD

**Issue by Supinic** [sindresorhus/got#2103]
#### Describe the bug

 - Node.js version: `18.0.0`
 - OS & version:  `Windows 10`, `Raspbian Buster`, `Ubuntu 20.04`
 - Got version: `11.6.0` and higher

#### Actual behavior

The `beforeError` hook fires regardless of whether or not the `throwHttpErrors` option is set to `false` and the request fails. This has been (erroneously, it seems?) changed in #1384 - more specifically in [as-promise/index.ts](https://github.com/sindresorhus/got/pull/1384/files#diff-4fd462a09629aa458e4fad7c6ec4a0393527acc587b657fff4f3d774490881a2L150-R120). This change wasn't mentioned anywhere in the `11.6.0` release, or in other releases since.

The behaviour is correct in all versions up until `11.6.0`, where this PR was merged.

#### Expected behavior

The `beforeError` hook should not fire if the `throwHttpErrors` option is set to `false`, and the request fails.

#### Code to reproduce

```js
const got = require("got");
const opts = {
    throwHttpErrors: false,
    hooks: {
        beforeError: [
            (e) => {
                console.log("beforeError hook", e.name);
            }
        ]
    }
};

(async () => {
    const res = await got.get("https://httpstat.us/400", opts);
    console.log("Response", res.body);
})();
```

In versions prior to `11.6.0`, the request response will be logged into console. In versions since, the `beforeError` hook will take precedence, log the error from it, and the response will not be logged. 

As an alternative to a code-based fix, the documentation could be adjusted instead, as it currently contains [no reference](https://github.com/sindresorhus/got/blob/main/documentation/9-hooks.md?plain=1#L267-L299) to such behaviour.

#### Checklist
- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
This unfortunately won't be easy to fix. In order to make a retry, an error is required. Then the `beforeRetry` hooks are called. If the error is still there (e.g. still getting 500) then `beforeError` is called. The error is then passed to the Promise implementation, it checks if `options.throwHttpErrors` is false. If it is, then returns `error.response` instead.

It wasn't possible to retry streams until https://github.com/sindresorhus/got/pull/1384 - to make the same logic there we would need to replace

https://github.com/sindresorhus/got/blob/0947389926700036f9fc4a80e05ddfefcdd3680a/source/core/index.ts#L796-L799

with

```js
		if (options.isStream && !isResponseOk(typedResponse)) {
			if (options.throwHttpErrors || (this.listenerCount('retry') > 0 && thisIsNotTheLastRetry)) {
				this._beforeError(new HTTPError(typedResponse));
				return;
			}
		}
```

but since `calculateDelay` hasn't been called yet, then `thisIsNotTheLastRetry` is unknown. And `calculateDelay` needs an error.

**Comment by szmarczak** [comment]
Also `HTTPError`s always have `error.response.body` defined. So it's not possible to retry `HTTPError`s for Stream API. On the last retry we'd need to check if `options.throwHttpErrors` is false. If false, then don't throw. But the body has been already read... so we have a few solutions:

1. get rid of `error.response.body` (severely degrades DX so it's rather a no), or
2. accept this behavior, or
3. apply a workaround: don't call `beforeError` hooks if `options.throwHttpErrors` is false.

**Comment by szmarczak** [comment]
We need to document this retry difference.

**Comment by szmarczak** [comment]
#2104 is a potential fix.
