### ISSUE TITLE
https option rejectUnauthorized is always set forcing node https module to ignore NODE_TLS_REJECT_UNAUTHORIZED

### ISSUE THREAD

**Issue by seal-hg** [sindresorhus/got#2149]
#### Describe the bug

 - Node.js version: 16
 - OS & version: Ubuntu
 
In source/core/options.ts the https option `rejectUnauthorized` is always set. If not to true or false then at least to undefined. But even if it is only set to undefined it is deactivating the consideration of environment variable NODE_TLS_REJECT_UNAUTHORIZED in the https module of Node.
You can easily avoid this by changing line 
https://github.com/sindresorhus/got/blob/73501b63fed981f7958e6f732d7c13791c050126/source/core/options.ts#L2442
to
```
			...(https.rejectUnauthorized && {rejectUnauthorized: https.rejectUnauthorized}),
```

#### Actual behavior

...

#### Expected behavior

...

#### Code to reproduce

```js
...
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Having multiple options to alter Node.js behavior is a bad idea. The only reasonable place to do so is the code.

**Comment by seal-hg** [comment]
Well, if having multiple options for doing something is a good or a bad idea is a matter of opinion. In this case following your opinion is breaking best practice of many years for test environments.

**Comment by szmarczak** [comment]
It's not best practice.

**Comment by fgreinacher** [comment]
@szmarczak @sindresorhus This is causing some issues in [`semantic-release/gitlab`](https://github.com/semantic-release/gitlab/issues/489). I understand your reasoning for not considering the env var, but it's really inconvenient for downstream tools, because all of us now need to provided dedicated configuration options for disabling the verification. Are you open to reconsider this or should we go ahead and solve it locally downstream?
