### ISSUE TITLE
Redirect consider as an error?

### ISSUE THREAD

**Issue by ryderlee** [sindresorhus/got#269]
I made a call to a url and that url return a 302 redirect to `got`, the problem is it raise as an error and fall into `.catch` instead of `.then`. May I ask if it is expected? Thanks.

**Comment by floatdrop** [comment]
@ryderlee it is an error, if you specify `body` option or making POST request.

**Comment by ryderlee** [comment]
But it doesn't make sense isn't it? It is so common to make a post call and then do a 302 redirect.

**Comment by floatdrop** [comment]
@ryderlee by HTTP specification browser (or client library) should ask user for resending POST body on redirects. `got` does not client interface to do this, so this considered an error.

**Comment by kvz** [comment]
You don't have to repost tho right? 

Consider the flow of:

1. POST username & password to server `/login`
2. Server accepts and 302 forwards to `/dashboard`
3. profit

When `followRedirect` is enabled, I'd expect got not to repost the credentials to `/dashboard`, but i do expect it to return the body of the dashboard. Does this make sense or no?

**Comment by AlexTes** [comment]
@kvz changing the method to GET on 301 or 302 is a [controversial topic](http://www.alanflavell.org.uk/www/post-redirect.html). We like to be safe. 

Because the people who designed HTTP/1.1 also recognized that people have a need for the scenario you described. That's why they created [303 - See Other](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303). Unfortunately, got currently does not support this either, but as soon as we fix #291 Got will.

**Comment by kvz** [comment]
Thanks for clarifying. I think I can easily change to 303 on our end, so i'll be tracking that PR and upgrading when I can. Thanks again!

**Comment by vardrop** [comment]
request-promise has the option `simple: false` which changes the expected behaviour for 3xx responses. 
as got does not have this option it makes it impossible to use request as an drop-in alternative.
