### ISSUE TITLE
Support raw deflate streams

### ISSUE THREAD

**Issue by pietermees** [sindresorhus/got#303]
It appears that some web servers do not properly implement the `deflate` transfer encoding. See for example: http://stackoverflow.com/a/9856879/7474128

We've encountered this in the wild, and have disabled `deflate` by overriding `Accept-Encoding: gzip,deflate` (the default) with `Accept-Encoding: gzip`.

Without this change, when got is presented with such a broken deflate stream, zlib throws an `incorrect header check` error and the request fails.

It seems that browsers have implemented "fuzzy logic" where they attempt decoding `deflate` properly first, and if that fails they assume that it's a raw deflate stream without headers or checksum.

Should got implement the same fuzzy logic like browsers do? Or disable `deflate`?

**Comment by sindresorhus** [comment]
I think this should be fixed in Node.js core if it's actually a big issue in the wild. We're just using the [`zlib.createUnzip()`](https://github.com/sindresorhus/decompress-response/blob/c5ca457170c190ca2baefa591aee3e38a5a8a0f8/index.js#L43) method. They could do the detection there. That way everyone would benefit instead of just Got users.

Resources:

- https://github.com/request/request/pull/2335
- http://stackoverflow.com/questions/37519828/how-can-we-distinguish-deflate-stream-from-deflateraw-stream/37528114#37528114

So please open an issue on Node.js instead.
