### ISSUE TITLE
Attempt a Retry when receiving TypeError

### ISSUE THREAD

**Issue by geosh03** [sindresorhus/got#310]
I am attempting to retrieve a URL from an email storage using "mailgun-js" and "got". I keep intermittently receiving the following error when executing my got command, "TypeError: Cannot read property 'storage' of undefined". This is mostly likely due to the email not being there at the time. I would like to keep retrying the got command until the body storage url is available. I am currently doing the following

got(output.items[0].storage.url, options, {retries: iter => iter < 10 && 500});

What it the proper way to keep attempting until I have the storage value in my output?

**Comment by AlexTes** [comment]
@geosh03 I'm afraid that's not possible. Before Got even gets your arguments your JavaScript runtime attempts to read the `items[0]` and finds `undefined`. That's fine, but `undefined` does not have properties, so continuing on, trying to read `.storage` the runtime blows up because it doesn't know what to give to Got. In short: you can't read properties that aren't there.

You could try something like:
```js
if (typeof output.items[0] !== 'undefined) {
  got(output.items[0].storage.url, options, {retries: numRetries => numRetries < 10 && 500});
}
```

There are other things you could likely improve but this has nothing to do with Got. There's usually very helpful people to be found on #node.js on Freenode (IRC) or [the gitter](https://gitter.im/nodejs/node).

**Comment by geosh03** [comment]
Indeed you are correct. I'm starting to see the issue is with mailgun-js. Thank you for your comments.
