### ISSUE TITLE
Not seeing content length header on certain files

### ISSUE THREAD

**Issue by rightaway** [sindresorhus/got#312]
If you do `curl -I http://webmaster.drtuber.com/export/big.csv`, it shows `Content-Length` header. But if you do `(await got('http://webmaster.drtuber.com/export/big.csv')).headers`, there's no content length to be found. On most files it works fine, but on some files I see a missing header.

**Comment by AlexTes** [comment]
I think node does 'chunked' transfer encoding by default. As per the [spec section 4.4 3.](http://www.ietf.org/rfc/rfc2616.txt) this means the content-length header _must not_ be included.

We could add an option to overwrite the default but with Node's streaming architecture the chunking probably makes a lot of sense. In any case, if you need this, explicitly setting the transfer-encoding header to any other accepted directive will work. You can read about the transfer encoding directives on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding). 

@rightaway were you reporting this as a bug or as a feature request?

**Comment by rightaway** [comment]
@AlexTes first I just wanted to understand the issue more. Is there anything special you can see about this file? I've tried with so many other files and `got` 99% of the time returns the `Content-Length` as expected.

I made a mistake in my original post, the command is actually `(await got('http://webmaster.drtuber.com/export/big.csv', { method: 'head' })).headers`, as it is a `HEAD` request. Shouldn't a HEAD request always return all headers?

**Comment by AlexTes** [comment]
Just a quick update, I was wrong, Got is the causing the chunked transfer-encoding. Node doesn't cause this by default.

Since compressing is more efficient Got sets the `Accept` header to `gzip,deflate` by default. Since the server serving the file agrees, it switches to compressing the file. However, the server only knows the size of the file uncompressed. So now it has two options:
* compress the whole file, check the new size, and then reply with the new content length
* compress and send in chunks, acknowledging that it doesn't know how many bytes it will be sending.

The latter is slightly faster because the server can compress and send at the same time. Ways to work around this are to overwrite our `Accept` header and set it to an empty string. Alternatively, you could compress the assets on the remote ahead of time so it does know how much data it will be sending.

Am I making sense?

**Comment by szmarczak** [comment]
Closed because of lack of response.
