### ISSUE TITLE
Support posting Arrays with json option

### ISSUE THREAD

**Issue by DerTieran** [sindresorhus/got#334]
Eventhough it was mentioned in #174:

> I'm ok with also supporting an array

Arrays are not supported with the `json` option (because of `isPlainObject`) so this fails:
```js
got.post('example.com', {
  json: true,
  body: [1, 2, 3]
})
```
Could you use something like [lodash's `isObjectLike`](https://lodash.com/docs#isObjectLike) instead of `isPlainObject` or test both `isPlainObject || isArray`?

**Comment by kevva** [comment]
Sounds valid to me.

**Comment by AlexTes** [comment]
@DerTieran total oversight on my part! Can we support sending arrays for both though?
That would also mean we don't have to split the logic regarding the argument validation like you have now.

**Comment by DerTieran** [comment]
@AlexTes I thought about that, but for `querystrings` your example was:
```js
> qstr(['alex'])
'0=alex'
```
I didn't see the use in that or ever encountered an API like that.
And because of your guy's **Complaint-Based-Development** 😉 I just added what I needed.

**Comment by DerTieran** [comment]
But when we are already talking I had another thought I first worked around the problem by just `JSON.stringify` the Array.
But then I needed to do everything by myself (setting headers etc.), what do you think about just skipping the `stringify` process.
You could also parse it first to see if it's valid, but I don't think that's needed.

**Comment by AlexTes** [comment]
@DerTieran
(Sorry for taking so long to respond!)
>I didn't see the use in that or ever encountered an API like that.

I could give use cases I imagine would be useful but I think it's more important to consider why I, and I'm pretty sure Sindre too, like _wish-based-development_ 😁. I like it because it keeps the code simple. We only add what we need. But in this case, counter-intuitively perhaps, supporting less complicates the code _more_. The way I see it you're adding a feature we don't need: explicitly avoiding encoding of arrays as querystrings.

Secondly, I feel we should only break with Node / browser behavior when it's helpful.

Thirdly, I can imagine a query like:
querying for a user and indicating you'd like some related or nested data to be included
```js
> querystring.stringify({
  name: 'alex',
  include: ['address', 'friends'],
}
```
retrieving data for a list of airports:
```js
> querystring.stringify({
  version: 1,
  airports: ['AMS', 'BKK', 'JFK'],
})
```

**Comment by AlexTes** [comment]
As for your second comment, I wouldn't be a fan I'm afraid. I do notice there's some friction with the option and I've coincidently suggested the opposite, splitting out the parsing (#264). Sindre indicated that the `json` option tries to be helpful for the common use-case and from what I've understood his and Vsevolod's experience says that needs both.

Does that make sense?

**Comment by DerTieran** [comment]
@AlexTes Sure I can see your point and I don't have a problem adding Array support to both.

As I said it was mainly I needed to send an Array as JSON, so I added it.

Regarding the second comment, I think thats a valid point. I think when Arrays are supported I wouldn't need to use `stringify` myself.

Should I just add Array support to `form` too?
Or do you guys want to discuss this and add it yourself?

**Comment by AlexTes** [comment]
@DerTieran Alright, I'm happy you agree 😄 .
Yea if you just update the PR as per my review and disregard the comment about adding a test, you're there and I can merge it!
