### ISSUE TITLE
Decode special characters

### ISSUE THREAD

**Issue by IonicaBizau** [sindresorhus/got#396]
```js
const got = require("got")
got("http://www.pravda.com.ua/news/2017/10/6/7157464/").then(res => {
    console.log(res.body.includes("Каховському"))
    // → false 
})
```

And the `req.body` contains special characters (which seem to have a different encoding):

```
� ����������� ����������� �������� ��
```

How to solve this? Is there a specific encoding we have to set?

**Comment by lukechilds** [comment]
You can pass the character encoding to be used with the Buffer directly through with `options.encoding`.

https://github.com/sindresorhus/got#encoding

**Comment by IonicaBizau** [comment]
@lukechilds Even when I'm using `encoding: null`, when I stringify it, those weird characters appear.

Thanks!

**Comment by lukechilds** [comment]
Hmmnn, yeah I just had a play, getting the same issue when I just load the page into a buffer with `http.request`.

Possibly an issue with weird encoding used by the web server? Node.js can definitely handle those characters if they're properly encoded with UTF-8:

```js
const buffer = Buffer.from('Каховському', 'utf8');
// <Buffer d0 9a d0 b0 d1 85 d0 be d0 b2 d1 81 d1 8c d0 ba d0 be d0 bc d1 83>

buffer.toString('utf8');
// 'Каховському'
```

Gonna close this issue as it seems like it's unrelated to Got. Feel free to re-open if you discover otherwise.

Don't forget to post back here with the solution if you find it! I would be interested to know.

**Comment by IonicaBizau** [comment]
OK, I've asked a Stackoverflow question: https://stackoverflow.com/q/46970062/1420197
