### ISSUE TITLE
`json` option?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/got#40]
`request` has this. Could be a nice shortcut.

It basically `JSON.stringify()` the input and sets the header `'content-type': 'application/json'` and `JSON.parse()` the output.

@kevva @floatdrop @julien-f Thoughts?

**Comment by kevva** [comment]
:+1: I like it.

**Comment by floatdrop** [comment]
:+1: 

P.s. just don't make it silent like [request](https://github.com/request/request/blob/9f844e29862a26771352f2a4f31d658da872af62/request.js#L1181-L1183).

**Comment by sindresorhus** [comment]
Hah, I saw that too. Of course not.

**Comment by julien-f** [comment]
Good idea, :+1:

**Comment by floatdrop** [comment]
If someone have ideas, how this option should behave in Stream mode, please share - I can't think nothing better than making it exclusive for callback mode.

**Comment by sindresorhus** [comment]
@floatdrop :+1:

**Comment by kevva** [comment]
@floatdrop, by using https://github.com/dominictarr/JSONStream.

**Comment by floatdrop** [comment]
@kevva awesome module, but I tend to leave streaming on feature releases because:
 * Streaming JSON is rare
 * It needs some additional options (for `parse` and `stringify`/`stringifyObject` calls)
 * It will not break compatibility, if we add it later

Now I'm digging through [issues](https://github.com/request/request/issues/718) with `json`-like options in other modules and implementing it right might be harder, than it looks (or I'm just over-complicating).

**Comment by kevva** [comment]
Yeah, haven't had a chance to look at it myself, but I agree we can leave this option for streams to future versions.

**Comment by floatdrop** [comment]
After reading some issues with `json` option in request one idea came up. All this noise around `json` option comes from the fact, that enabling it have two separate effects:

 1. input - it enables serializing of `body` (and add headers, if they not set)
 2. output - parses incoming JSON

So, why don't just split them apart? Now, if we pass `Object` in `body`, we will get next error: `TypeError: first argument must be a string or Buffer`. What if we serialize it to JSON in this case (without setting any options)? Anyway we can't send it as is, so this seems reasonable. But two things needs to be considered:

 1. is it true, that most users want to serialize objects in `body` option instead of throwing error?
 2. if so, should we take care of `toString` property as well?

**Comment by floatdrop** [comment]
Partially implemented in `2.7.0` :tada:
