### ISSUE TITLE
Clarify cache behaviour

### ISSUE THREAD

**Issue by rarkins** [sindresorhus/got#423]
Thanks @lukechilds for adding caching to the library. Would you mind if I ask for a couple of clarifications?

I'd like to use the npmjs registry as my example. They return headers like so:
```
Cache-Control: max-age=300
ETag: W/"5a14f9ea-234b93"
Last-Modified: Wed, 22 Nov 2017 04:15:38 GMT
```

Consider a long-running app (hours/days) that queries npmjs regularly.

1. If queries are made for the exact same package (URL) twice within 5 minutes, will the second receive an answer directly from cache, or only after a conditional query with 304 response?
2. Will cached values ever "expire", or will they remain in cache indefinitely for use in `If-Modified-Since` and `If-None-Match` headers in future?

My current approach in got v7 is:
- check `keyv` cache for matching url
- if not found, `got` the request
- filter json result for data I need
- save filtered json using `keyv` with expiry 5 minutes

So I'm wondering how replacing this with `got` v8's implicit caching would impact things. (a) it will obviously store the entire (huge) npm responses as opposed to my filtered ones, but (b) it would result in a lot more 304 responses assuming `got` v8 keeps the "old" values longer than 300s.

**Comment by lukechilds** [comment]
@rarkins Yeah sure, nice work on Renovate btw!

> 1. If queries are made for the exact same package (URL) twice within 5 minutes, will the second receive an answer directly from cache, or only after a conditional query with 304 response?

We follow [RFC 7234](http://httpwg.org/specs/rfc7234.html) so if the cached response is still valid it'll be pulled directly from the cache. If the cached response has expired we send an `If-Modified-Since`/`If-None-Match` revalidation request, then if we get a 301 response the cached body is used (with updated headers from the request), if we don't get a 301 then the cached response is deleted and the new response is returned.

> 2. Will cached values ever "expire", or will they remain in cache indefinitely for use in `If-Modified-Since` and `If-None-Match` headers in future?

As far as Got is concerned they will be stored indefinitely for future use with revalidation requests. If a request fails to be revalidated it will be deleted. However all storage is controlled by Keyv, so you can back Keyv with an LRU cache to limit it to a certain size/number (e.g `quick-lru`, Redis).

You can read more about the cache functionality on the underlying cache module's repo: https://github.com/lukechilds/cacheable-request

@sindresorhus Do you think it'd be worth giving a brief summary of the supported caching behaviour and referring people to `cacheable-request` for more info in the readme?

Currently we only mention it's "RFC compliant" without going into any detail on what that covers. Somebody on Twitter also asked for more clarification.

**Comment by sindresorhus** [comment]
> Do you think it'd be worth giving a brief summary of the supported caching behaviour and referring people to cacheable-request for more info in the readme?

Yeah, I think it would be useful with a succinct summary in the Got readme.

**Comment by rarkins** [comment]
@lukechilds thanks for the clarification.

Great that the behaviour is to suppress the round trip if the result is still valid, because Renovate is typically network-bound waiting on API responses.

I think I will try as you suggest and just let `got` + cache do its thing for now and fall back to `quick-lru` if I find memory use is too high, but right now memory use is the least concern so may not be a problem at all!

My question is answered, but I will leave this open in case you wanted to use it as a reminder for documenting the readme.
