### ISSUE TITLE
Revert readme example async changes

### ISSUE THREAD

**Issue by Siilwyn** [sindresorhus/got#428]
First want to say I've been using `got` for a while now, love it, thanks for creating this module! :1st_place_medal: 

I often return to look at the examples in the readme and noticed they changed to use the new `async`/`await` in https://github.com/sindresorhus/got/commit/a4facf311d886e29217527ea4ee1c0990af04af3#diff-0730bb7c2e8f9ea2438b52e419dd86c9.

Wondering why? In my opinion this hurts readability, the self executing function and the variable declaration add more noise. Would you consider reverting this change please?

**Comment by sindresorhus** [comment]
I find async/await more readable, but I guess that's debatable. The wrapper is only there because await can't *yet* be used top-level. It will hopefully eventually happen and we can then remove the wrapper. Even with the boilerplate, I still find it more readable than `.then()`, so not interested in changing that, sorry.
