### ISSUE TITLE
got.stream cannot resume download

### ISSUE THREAD

**Issue by Nelife** [sindresorhus/got#453]
He!
I have a problem!
I use got.stream to stream url to download. Put it cannot resume download.
Thank you so much

```
app.get('/test', function (req, res) {
    const url = 'https://c2-sd-vdc.nixcdn.com/PreNCT12/HoaTimNguoiXuaKaraoke-QuangLe-4601841.mp4?st=rclWIYzqLN_lij8UpM9Z0Q&e=1517999354&t=1517912951366';
    got.stream(url)
        .on('response', (response) => {
            res.statusCode = response.statusCode;
            Object.keys(response.headers).forEach(key => {
                res.setHeader(key, response.headers[key])
            })
        })
        .on('error', function (e) {
            console.log(e);
        })
        .pipe(res);
});
```

![icgbc](https://user-images.githubusercontent.com/12018657/35863105-34a729d0-0b80-11e8-9af0-3b79904addf1.jpg)
![ws1q3](https://user-images.githubusercontent.com/12018657/35863104-3475243a-0b80-11e8-95dd-38c0abb0d590.jpg)
![tgxxm](https://user-images.githubusercontent.com/12018657/35863106-34d812e8-0b80-11e8-8b5f-53f31fa5024c.jpg)

**Comment by lukechilds** [comment]
Because you're just re-downloading the file on every request and piping it through. Got is functioning as expected.

If you want to allow partial downloads for simultaneous download connections or resumable downloads you need to implement range requests in your application code or use a proxy lib that does this for you.

Helpful links:

https://en.wikipedia.org/wiki/Byte_serving
https://tools.ietf.org/html/rfc7233
