### ISSUE TITLE
Remove documentation's warning that body is mutually exclusive with stream mode

### ISSUE THREAD

**Issue by davidtheclark** [sindresorhus/got#474]
https://github.com/sindresorhus/got#body says the `body` option "is mutually exclusive with stream mode." 

However, it looks like there is code that makes `body` work in stream mode:

https://github.com/sindresorhus/got/blob/9a646a39e6761d0914694f9d97bf332b06fdb8f5/index.js#L435-L454

I've tried using stream mode with `body` as a stream and a string, and it worked fine in both cases. The only trouble I hit was if I tried to use a plain object and `json: true` (to parse it): an error was thrown saying JSON-mode was not compatible with stream-mode.

I'm happy to submit a PR modifying the docs, but wanted to double-check about the intentions. Is the current behavior correct — in which case we should eliminate the line about `body` being "mutually exclusive with stream mode"?

**Comment by sindresorhus** [comment]
Stream-mode refers to using `got.stream()` and piping the response. The `body` option is only for when using `got()` (Not `got.stream()`), and it can be a stream too, that's not related to stream-mode.

**Comment by MikeyBurkman** [comment]
Yeah I think there's a confusion in the docs between request.body and response.body. What @davidtheclark is referring to is that the docs say you can't provide a body in the request while in stream mode, which (I assume) is not correct. Stream mode only affects how the response is parsed and returned to the caller, right?

**Comment by davidtheclark** [comment]
I noticed today that adding a file with the `body` option is the only way to get an estimate of its size, which improves progress events. So it seems to me that using `body` in stream mode might be not just a *working* option but also the *preferred* option.

**Comment by davidtheclark** [comment]
Another point of confusion: If a stream-mode request that *could* have a body (post, patch, put) *does* have a `body` option, you do not need to call `req.end()` yourself; but if it *does not* have a `body` option, or the `body` is falsy, you *do* need to call `req.end()`. I wonder if that can be smoothed out. But, again, I'm not really sure what the *intention* is around `body` in stream mode.

**Comment by MikeyBurkman** [comment]
I'm not really sure why "stream mode" would ever need to be specified for the *request*. If the opts.body is a readable stream, then the body should be streamed, and when the stream ends, the request should be ended automatically. 

Stream mode *should* only be there to specify "stream the response instead of loading it all into a single object in memory". I really think that stream mode should only affect the response. 

Disclaimer: I'm just some random dude and I'm just describing how I think the library should behave. I do not know exactly what it actually does. Hence why there's this issue -- the docs are not clear on this.

**Comment by szmarczak** [comment]
I did some digging:

1. `options.body` was added in 2c8ee3f
2. WritableStreams were added in c080439

It's mutually exclusive, because if you provide the `body` option it's no longer writable:

https://github.com/sindresorhus/got/blob/c080439382f1619fc664fcdb81788e4466d94b0e/index.js#L105-L110

The same piece of code you can find in v8.3.2 (the newest version as of 31.07.2018):

https://github.com/sindresorhus/got/blob/ad7b361dcb2490c3864b845b979b756f13f7d89b/index.js#L441-L445

https://github.com/sindresorhus/got/blob/ad7b361dcb2490c3864b845b979b756f13f7d89b/index.js#L457-L460

**Comment by davidtheclark** [comment]
@szmarczak The documentation still isn't clear, or there wouldn't be this issue. I don't see anywhere that says "stream mode" means you're piping a stream into the *request*, and has nothing to do with whether your *response* is a stream or not. That's particularly confusing when it says things like `body` can be a `stream.Readable` but "is mutually exclusive with stream mode". 

If the phrase "stream mode" were universally replaced with "piping a stream into the request", that would be accurate *and* clarify things, right? Are you open to a PR with that change?

**Comment by szmarczak** [comment]
It doesn't matter if `body` is a string or `stream.Readable`. I think it's clear if you provide `body` then you want to pipe it to the request :)

Anyway, I agree, we can clarify that sentence. Something like `Providing this option will make the stream read-only.`? I'm open to your ideas :)

@sindresorhus What are your thoughts?
