### ISSUE TITLE
Headers are case sensitive

### ISSUE THREAD

**Issue by CBenni** [sindresorhus/got#612]
When supplying headers (notably "Accept"), the keys are key sensitive, which, for me, broke my apps since I was supplying `{json: true}` alongside a header object with an `{Accept: "application/something.else"}`

The normalize-arguments code then overwrote my Accept header with the accept header.
I can submit a PR to fix this if you like, otherwise giving it a gotcha note on the docs would be nice.

**Comment by szmarczak** [comment]
Could you please provide an example?

**Comment by alextes** [comment]
This issue is frustratingly hard to get at somehow >:-[
Grr, issues that I don't understand I find so hard to let go 😅 . Anyway, the main issue is obvious, there are a few places where we respond to or add headers whilst inspecting `options.headers` and assume they're in lower case already. Normalization should lowercase all headers and prefer the passed ones. Example is: `normalize-arguments.js` where we add an `accept` header if the option `json: true` is present and no lowercase `accept` is set,  ignoring the fact there might be some `Accept` or `ACCEPT` header present already. I'll submit a failing test.

If you're interested why we have a green test that should be red 🤔 , here's my best guess: ~We actually have a test for this, and it passes: `transform names to lowercase`. It correctly overwrites the default user agent with a test user agent but , Node opts for the uppercase header. The best I can come up with is that~ FINNALLY! The reason is that `cacheable-request` uses `lowercase-keys` and this package overwrites keys _in the order the keys were set in_. So keys with the same lowercase name set later in the execution flow overwrite earlier ones. The `user-agent` happens to be the one header we merge the user options in and that's the reason the test passed.

All logic depending on other headers is wrongly ignoring othercased headers.
