### ISSUE TITLE
DNS cache

### ISSUE THREAD

**Issue by roccomuso** [sindresorhus/got#661]
I do understand that mabe it's not the purpose of this lib (feel free to close in case).
But would be useful adding a dns cache layer.
It's one of the common problem nowadays with huge number of requests. It doesn't cache dns lookups or anything. Maybe it's worth just mentioning this in Readme.

What's the cleanest way to deal with it?

**Comment by sindresorhus** [comment]
Node.js has ability to get the TTL of DNS lookups: https://github.com/nodejs/node/pull/9296 So we could potentially implement a simple automatic cache based on that.

Some prior art (which all seems to require setting TTL manually):

- https://github.com/yahoo/dnscache
- https://github.com/devswede/dns-cache
- https://github.com/eduardbcom/lookup-dns-cache
- http://blog.dmcquay.com/optimization/2017/06/14/nodejs-connection-pooling-and-dns-caching.html

**Comment by morozRed** [comment]
@sindresorhus I would like to work on that

**Comment by brandon93s** [comment]
I think the ideal implementation would be an _automatic_ TTL cache by simply respecting the TTL of the DNS record itself. If the upstream DNS server(s) are respecting TTL to spec, they will be caching for the same TTL meaning a value lower than set on the DNS record is unnecessary. 

![image](https://user-images.githubusercontent.com/4730164/48871829-60479400-edb4-11e8-983d-8cf048ffcc5b.png)

As for a size limit, I don't think it's necessary. Absolute worst case, a domain (63 characters) and IPv6 address (128 bit) pair are represented in 79 bytes. That means you can store 12,658 cached DNS entries per megabyte of memory. In practice, you'd get 25,000+ since domains are shorter. For long running processes, we could implement an asynchronous tick (e.g. `setInterval`) to clean out expired entries every few minutes if that becomes necessary.

We should however offer an option to disable it. This leaves us with two modes:
- On, fully automated, no limit
- Off

Just my $0.02.

**Comment by morozRed** [comment]
btw can anyone assign this issue to me, because I'm already working on it (if it's necessary)

**Comment by pietermees** [comment]
Wouldn't it make sense to simply accept a `lookup` function like the Node APIs do? Then you can use one of the existing DNS cache implementations like `redns`?

**Comment by morozRed** [comment]
@pietermees default `dns.lookup` method is not supporting providers `ttl` which we want to support. 
Also we want to support different types storage (i.e. `keyv`).

About `dns.resolve()`, `dns.resolve*()`
> These functions are implemented quite differently than dns.lookup(). They do not use getaddrinfo(3) and they always perform a DNS query on the network. This network communication is always done asynchronously, and does not use libuv's threadpool.
As a result, these functions cannot have the same negative impact on other processing that happens on libuv's threadpool that dns.lookup() can have.
They do not use the same set of configuration files than what dns.lookup() uses. For instance, they do not use the configuration from /etc/hosts.

For more info please refer to [this doc].(http://nodejs.cn/doc/node/dns.html#dns_implementation_considerations)

And there is definetily no point to add another dependency because it's not so much code to do.

**Comment by pietermees** [comment]
@morozRed sorry, I should have been clearer. I meant to ask why DNS caching should be part of `got` rather than an external thing you can plug in.

The reason why I ask is that Node APIs already allow overriding DNS lookups on TCP/HTTP/HTTPS/H2 connects by providing a custom `lookup` function. Existing packages like `redns` and other leverage that to provide DNS caching capabilities similar to what you're trying to implement here.

My main point is that adding a `lookup` option to `got` similar to the `lookup` option in [`socket.connect`](https://nodejs.org/dist/latest-v11.x/docs/api/net.html#net_socket_connect_options_connectlistener). That would allow you to easily plug in any of the existing DNS cache packages.

**Comment by morozRed** [comment]
@pietermees oh ok, well the idea was to make automatic DNS cache, but still, we can add an option to override lookup method:
```
await got('google.com', { lookup: CUSTOM_DNS_CACHE.lookup });
```

**Comment by pietermees** [comment]
Having played around with some of the DNS cache implementations that are around, I think you'll find that you can't easily provide a default DNS cache that is fully transparant (i.e. handles DNS exactly the same way as the system would).

As you've indicated you have to use the `dns.resolve` API which behaves differently than `getaddrinfo`. This impacts `/etc/hosts` but also IPv6 vs IPv4 preferences etc.

With that in mind, I don't think it's possible to provide an implementation that's enabled by default and does not change semantics for all `got` users.

Hence my suggestion to use the `lookup` option (I didn't know that already worked, thanks!).
1. It's already available
2. You can use an existing DNS cache package without having to write anything
3. If it can't be enabled by default, you'd have to provide an option to activate it anyway, so it's the same amount of work as just providing a custom `lookup` function

**Comment by morozRed** [comment]
ok so @sindresorhus @brandon93s what do you guys think about it? Maybe I can update the docs here at least?

**Comment by szmarczak** [comment]
What should we do when the DNS server offers us multiple IP addresses? Should we cache them?

**Comment by morozRed** [comment]
@szmarczak you can cache all the addresses and then use round-robin strategy. But I'm not sure now if we do need to implement custom cache if you can simply pass package or custom lookup function to got.

**Comment by morozRed** [comment]
@szmarczak [this package](https://github.com/eduardbcom/lookup-dns-cache) supports provided DNS TTL. I've been working on this issue but then I got stuck because of this discussion.

**Comment by wtgtybhertgeghgtwtg** [comment]
> It's way too bloated.

To be fair, that's mostly because it pulls in `async` (to get IPv4 and IPv6 stuff in parallel) and `lodash` (to do input validation).  If the maintainer's willing, it wouldn't be that hard to pull those out.

**Comment by szmarczak** [comment]
https://github.com/szmarczak/cacheable-lookup

**Comment by szmarczak** [comment]
@sindresorhus Any ideas on how to implement `cacheable-lookup` into Got? Should we reuse `options.cache` or use `options.dnsCache` instead?

**Comment by sindresorhus** [comment]
`options.dnsCache`
