### ISSUE TITLE
stream with error response

### ISSUE THREAD

**Issue by futurist** [sindresorhus/got#669]
#### Describe the bug

 - Node.js version: 8.9
 - OS & version: macOS

#### Actual behavior
I'm using below code to share resource with other website:

```js
// express with cors enabled, listening on: 8080
app.all('/cors/*', async (req, res, next) => {
  req.pipe(got.stream(req.params[0], {
    method: req.method,
    headers: req.header,
    stream: true
  })).pipe(res)
}
```
Sometimes its throw below error:

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

RequestError: connect ECONNREFUSED 10.125.25.106:8001
    at ClientRequest.request.once.error (/Users/pro/james/app/node_modules/_got@9.3.2@got/source/request-as-event-emitter.js:162:14)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:187:15)
    at ClientRequest.origin.emit.args [as emit] (/Users/pro/james/app/node_modules/_@szmarczak_http-timer@1.1.1@@szmarczak/http-timer/source/index.js:36:11)
    at Socket.socketErrorListener (_http_client.js:391:9)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at EventEmitter.emitter.on.args (/Users/pro/james/app/node_modules/_got@9.3.2@got/source/as-stream.js:69:58)
    at EventEmitter.emit (events.js:182:13)
    at ClientRequest.request.once.error (/Users/pro/james/app/node_modules/_got@9.3.2@got/source/request-as-event-emitter.js:166:14)
    at Object.onceWrapper (events.js:273:13)
    [... lines matching original stack trace ...]
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
```

#### Expected behavior

Should work for any url and methods

#### Code to reproduce

From the website `10.125.25.106:8001`, open console and run below code:

```js
fetch('http://localhost:8080/cors/http://mysite.com?query=1234')
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
```js
// express with cors enabled, listening on: 8080
app.all('/cors/*', async (req, res, next) => {
  req.pipe(got.stream(req.params[0], {
    method: req.method,
    headers: req.header,
    stream: true
  })).pipe(res)
}
```

You're missing `error` handler there.

```js
app.all('/*', async (req, res, next) => {
    const stream = got.stream(req.params[0], {
        method: req.method,
        headers: req.header,
        stream: true
    });

    stream.on('error', error => {
        res.statusCode = 500;

        res.end(error.toString()); // never do that unless you're debugging
    });

    req.pipe(stream).pipe(res);
});
```

**Comment by cookch10** [comment]
Hi @szmarczak,

I was looking through the issue list, and this one looked a lot like what I am trying to accomplish, which is to use this package as part of an express server middleware.

I need to make requests to resources on external domains, and then serve that back up within my local server with the response headers from the external domain modified.

I have this working for the most part, with one caveat.  That is, I am not sure how I can modify the response header before it's piped to the middleware response when using streams (the hook that I think I would need to use would be the afterResponse hook. which is not available with streams).

I was looking through the issue list, and this one looked a lot like what I am trying to accomplish, however, I was curious about this line specifically in your example:
```js
req.pipe(stream).pipe(res);
```

By creating `got.stream()`, isn't that immediately invoking the request?  Can it be piped into the request object?  I've been struggling with this for a couple of days now, so I thought I'd ask since things may have changed from when you last commented on this issue.

I've tried your example, but this yields a 400 (bad request) server error.  This is my current example which works, but does not currently allow modifying the response headers from the got request:
```js
  app.get('/external', (req, res, next) => {
    const stream = require('stream');

    const { CookieJar } = require('tough-cookie');

    const { promisify } = require('util');

    const got = require('got');

    const pipeline = promisify(stream.pipeline);

    const jar = new CookieJar();

    const setCookie = promisify(jar.setCookie.bind(jar));

    const { search } = req._parsedUrl;

    const searchUrl = search ? search : '';

    const uri = `https://www.external.com${req.path}${searchUrl}`;

    const gotInstance = got.extend({
      hooks: {
        beforeRequest: [
          options => {
            console.log(options);
          }
        ]
      }
    });

    try {
      _pipeline(gotInstance.stream(uri, { decompress: false, cookieJar: jar }), res);
    } catch (error) {
      next();
    }
  });
```

I've been struggling with this one, so any insight you may have would be appreciated.
