### ISSUE TITLE
Target Size

### ISSUE THREAD

**Issue by tyrsius** [sindresorhus/got#769]
When _got_ started it was targeting _request_ because of its bloated install size. Since install size has a strong correlation with load & parsing time this made a lot of sense.

_got_ started around 50kb. It's now up to 300kb.
It seems to be trending down the same path _request_ took.

I would like to understand what the target size of this library is; as in, what would be an unacceptable limit to cross? It isn't stated anywhere, and there are no automated tools or checks to verify that a size threshold has been crossed. I think it is important to agree on and stick to a size limit, lest you end up passing 1mb without realizing it.

**Comment by szmarczak** [comment]
> got started around 50kb. It's now up to 300kb.

Let's review:

At [v2.1.0](https://github.com/sindresorhus/got/tree/v2.1.0) it started with [17KB](https://packagephobia.now.sh/result?p=got@2.1.0). Then it jumped to [250KB](https://packagephobia.now.sh/result?p=got@2.2.0) ([v2.2.0](https://github.com/sindresorhus/got/tree/v2.2.0)).
At [v5.7.1](https://github.com/sindresorhus/got/tree/v5.7.1) it rised up to [330KB](https://packagephobia.now.sh/result?p=got@5.7.1). Then it fell down to [75KB](https://packagephobia.now.sh/result?p=got@6.0.0) ([v6.0.0](https://github.com/sindresorhus/got/tree/v6.0.0)).
At [v6.7.1](https://github.com/sindresorhus/got/tree/v6.7.1) it rised up to [110KB](https://packagephobia.now.sh/result?p=got@6.7.1).
At [v7.1.0](https://github.com/sindresorhus/got/tree/v7.1.0) it rised up to [180KB](https://packagephobia.now.sh/result?p=got@7.1.0).
At [v8.0.0](https://github.com/sindresorhus/got/tree/v8.0.0) it was [500KB](https://packagephobia.now.sh/result?p=got@8.0.0) and stayed on that level until [v9.0.0](https://github.com/sindresorhus/got/tree/v9.0.0) - [250KB](https://packagephobia.now.sh/result?p=got@9.0.0).

At the current latest release ([v9.6.0](https://github.com/sindresorhus/got/tree/v9.6.0)) it is [300KB](https://packagephobia.now.sh/result?p=got@9.6.0) (source has 85KB).

Got was having only two maintainers for a long time (three at v7). I joined Got together with other people some time after the 8 release. As you can see there is ***lots of brand new features*** and ***the install size has dropped***. We're trying our best to decrease the install size without having any impact on the Got features.

Please take a look at this [Install size of the dependencies](https://github.com/sindresorhus/got#install-size-of-the-dependencies). Each package has its purpose:
 - [@sindresorhus/is](https://github.com/sindresorhus/is) (42KB) is used to check types, like if that's a string, an array, an empty object etc. Very useful for normalizing options and validating them.
 - [@szmarczak/http-timer](https://github.com/szmarczak/http-timer) (10KB) is used to get HTTP timings, like the Request package.
 - [cacheable-request](https://github.com/lukechilds/cacheable-request) (134KB) is used to cache requests.
 - [decompress-response](https://github.com/sindresorhus/decompress-response) (11KB) is used to decompress response.
 - [duplexer3](https://github.com/floatdrop/duplexer3) (7KB) is used to generate a Duplex stream, so the same stream can pass data to the request and provide response.
 - [get-stream](https://github.com/sindresorhus/get-stream) (36KB) is used to safely get the whole content of a stream. We need it for Promise support.
 - [lowercase-keys](https://github.com/sindresorhus/lowercase-keys) (3KB) is used to lowercase the headers.
 - [mimic-response](https://github.com/sindresorhus/mimic-response) (5KB) is used to clone the response. First, we generate a progress stream from the original response and then clone the properties.
 - [p-cancelable](https://github.com/sindresorhus/p-cancelable) (14KB) is used to make cancelable promises so you can abort the request.
 - [to-readable-stream](https://github.com/sindresorhus/to-readable-stream) (5KB) is used to convert buffers to streams, so you can access progress events.

I don't think we can remove any dependency at this point.

> It seems to be trending down the same path request took.

I disagree. See the [Comparison](https://github.com/sindresorhus/got#comparison) :)

> I would like to understand what the target size of this library is; as in, what would be an unacceptable limit to cross? It isn't stated anywhere, and there are no automated tools or checks to verify that a size threshold has been crossed. I think it is important to agree on and stick to a size limit, lest you end up passing 1mb without realizing it.

Well, we haven't set any limit. We just aim for the lowest install size with the most features. The chance that we will cross 1MB is very low.

If you only need to make request and retrieve the response we recommend [ky](https://github.com/sindresorhus/ky/) (35KB) - it's maintained by the same people. To use it with Node you'll need [ky-universal](https://github.com/sindresorhus/ky-universal) - it's 450KB in total because of the ponyfills, so use it if you need something to work both on server side and client side. If you don't need all that fancy Node stuff make sure to check out [Deno](https://github.com/denoland/deno) :)

**Comment by tyrsius** [comment]
Yes, the same note about ky is on the README/front page. Since this is a library for Node comparing it to a browser-only lib isn't very useful, and as you point out ky-universal is _larger_ than this library.

I actually think several of those dependencies, especially _is_ (42kb for _type checking_?), could be trimmed down. Focusing on size is difficult, but since this library started as a lightweight alternative to _request_ it seems like a worthwhile exercise. Sometimes trimming the fat means re-implementing portions of other libraries that do more than necessary.

When I say trending down the same path as _request_ I don't mean feature-wise, I mean _bloat-wise_. Between v7 and v8 the size tripled. I don't think the chance that it gets to 1mb is very low, especially if automated checks or at least a written limit aren't in place. You've tripled before, what is going to stop it from happening again?

Doing _everything_ in one library isn't always the best approach. Some of these features could be broken out into sidecar libraries.

**Comment by sindresorhus** [comment]
> I actually think several of those dependencies, especially is (42kb for type checking?), could be trimmed down.

That package is important for correctness. Correctness is more important than size. We're happy to entertain trimming suggestions, but our priority is having a stable and bug-free HTTP client. 42 KB is the install size. The actual JS file is 11 KB.

> When I say trending down the same path as request I don't mean feature-wise, I mean bloat-wise. Between v7 and v8 the size tripled.

Writing a production-ready HTTP client is very complicated. We fixed a *lot* of bugs in those releases. It grew in size because Got now handles more edge-cases and real world scenarios.

**Comment by tyrsius** [comment]
> Writing a production-ready HTTP client is very complicated. We fixed a lot of bugs in those releases. It grew in size because Got now handles more edge-cases and real world scenarios.

Absolutely, and I don't mean to trivialize the effort or complexity of the task. I don't want to advocate for removing features or bug-checking or stability. What I want to advocate for is an automated check for package size to keep it in everyone's mind. There are tools (like [size-limit](https://github.com/ai/size-limit)) that can do this as part of a test run.

Correctness and stability and featurees may all out-rank size, but it should still be considered.
