### ISSUE TITLE
Ambiguous URLs

### ISSUE THREAD

**Issue by rhodgkins** [sindresorhus/got#783]
#### Describe the bug

 - Node.js version: 8.15
 - OS & version: macOS
 - Got version: 9.6.0

#### Actual behavior

Setting up a got instance using `baseUrl` of `https://analyticsreporting.googleapis.com/v4`, and then using it with URLs with `:` in them (`/reports:batchGet`) cause an exception.

#### Expected behavior

I'd expect the following URL to be used: `https://analyticsreporting.googleapis.com/v4/reports:batchGet`

#### Code to reproduce

```js
const https = require('https')
const client = got.extend({
   baseUrl: 'https://analyticsreporting.googleapis.com/v4',
   agent: new https.Agent({ keepAlive: true }),
   encoding: null,
   decompress: false,
   throwHttpErrors: false
}
client.stream('/reports:batchGet')
```

Exception:

```
{ message: 'Unsupported protocol "reports:"',
  stack: 'UnsupportedProtocolError: Unsupported protocol "reports:"\n    at get (/<dir>/node_modules/got/source/request-as-event-emitter.js:53:10)\n    at Immediate.setImmediate [as _onImmediate] (/<dir>/node_modules/got/source/request-as-event-emitter.js:305:10)\n    at <anonymous>',
  name: 'UnsupportedProtocolError',
  host: undefined,
  hostname: '',
  method: 'GET',
  path: 'batchGet',
  socketPath: undefined,
  protocol: 'reports:',
  url: 'reports:batchGet',
  gotOptions: 
   { path: 'batchGet',
     protocol: 'reports:',
     hostname: '',
     hash: '',
     search: '',
     pathname: 'batchGet',
     href: 'reports:batchGet',
     retry: 
      { retries: [Function],
        methods: {},
        statusCodes: {},
        errorCodes: {} },
     hooks: 
      { beforeError: [],
        init: [],
        beforeRequest: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: [] },
     decompress: false,
     throwHttpErrors: false,
     followRedirect: true,
     stream: true,
     form: false,
     json: false,
     cache: false,
     useElectronNet: false,
     baseUrl: 'https://analyticsreporting.googleapis.com/v4/',
     agent: 
      { domain: null,
        _events: { free: [Function] },
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: { keepAlive: true, path: null },
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: { map: {}, list: [] } },
     encoding: null,
     method: 'GET' } }
```

Note that doing the following in the Node REPL also simulates the same problem - so it's not a Got issue I guess but then I can't really work out what's going on! I'm only raising it here because from the [example in the README](https://github.com/sindresorhus/got#baseurl), using the above code looks like it should work!

```
> new url.URL('reports:batchGet', 'https://analyticsreporting.googleapis.com/v4/').toString()
'reports:batchGet'
```

From reading [other issues](https://github.com/sindresorhus/got/issues/562#issuecomment-412796684), this works however, but isn't ideal! It might be a case for further URL normalisation?

```
>new url.URL('./reports:batchGet', 'https://analyticsreporting.googleapis.com/v4/').toString()
'https://analyticsreporting.googleapis.com/v4/reports:batchGet'
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
@sindresorhus Any ideas on how to properly fix this? It could be solved by forcing the use of `/` at the beginning of the `url` argument.

**Comment by sindresorhus** [comment]
> It could be solved by forcing the use of / (we would convert / -> ./) at the beginning of the url argument.

Either that or we just don't use `new URL()` to combine the URL and `baseUrl`. We could do it manually too, right?

// @sholladay

**Comment by sholladay** [comment]
The URLs `/reports:batchGet` and `reports:batchGet` have _very_ different meanings. The former says "bring me to the origin (root of the domain) of the current website and then append `/reports:batchGet` as the path". The latter says, "I don't care about the current website, let's go to a brand new URL from scratch, let's use the `reports` protocol instead of HTTP, and the domain name is `batchGet`".

Based on what you wrote about your expectations, neither of these is quite what you are expecting. The former is pretty close, except it won't have `/v4` in the final URL. That's because URLs that begin with a `/` are origin-relative, not page-relative, when resolved by a URL resolver like [window.URL()](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL).

In [Ky](https://github.com/sindresorhus/ky), we decided to have an option called `prefixUrl` that does _not_ do URL resolution. Instead, it acts as a simple prefix, because that seems to be what people really want most of the time, and URL resolution isn't the most intuitive thing in the world (though it can be very useful).

I would argue that Ky and Got should both have the same behavior here. They should support a `prefixUrl` that is very simple to use and understand, and potentially also a `baseUrl` option, which should do standards-compliant URL resolution, where it's your responsibility to learn the details of how URL resolution works.

Putting that all together, if Got hypothetically supported `prefixUrl`, then that's what you'd want to use in your case.

```
const https = require('https')
const client = got.extend({
   prefixUrl: 'https://analyticsreporting.googleapis.com/v4/',
   agent: new https.Agent({ keepAlive: true }),
   encoding: null,
   decompress: false,
   throwHttpErrors: false
}
client.stream('reports:batchGet')
// https://analyticsreporting.googleapis.com/v4/reports:batchGet
```

**Comment by sindresorhus** [comment]
@sholladay The Got `baseUrl` is documented to behave like the Ky `prefixUrl` option in that it’s only supposed to prefix, so I don’t think anyone would expect any kind of resolution. I think it would be confusing to have both a baseUrl and prefixUrl option, especially in Got. How about we rename the `baseUrl` option to `prefixUrl` and manually combine them instead of using `new URL`, like we do in Ky? That would be my preferred solution. The open question is whether we should enforce not using the `/` prefix like we do in Ky? Thoughts?

**Comment by szmarczak** [comment]
After some thinking I agree with you. I'll make a PR then :)

**Comment by sindresorhus** [comment]
@szmarczak @sholladay Any thoughts on:

> The open question is whether we should enforce not using the / prefix like we do in Ky?

**Comment by szmarczak** [comment]
I agree.

**Comment by sholladay** [comment]
Oh you're right, it is documented that way. I looked at the source and [this line](https://github.com/sindresorhus/got/blob/6eaa81ba8db87340bbdbd79ef91594803f37b854/source/normalize-arguments.ts#L131) does URL resolution. Along with the option name, I just assumed that was the documented behavior.

Changing this is a pretty significant change. And people may be relying on some of the URL resolution semantics, including this bit from the documentation:
> If you specify an absolute URL, it will skip the baseUrl.

Ky doesn't do that, precisely because of issues like this. According the the URL standard, `reports:batchGet` is an absolute URL. But the OP doesn't expect that to completely override the input URL. So in order to be more user-friendly, I think `prefixUrl` should _only_ be a prefix, which does not try to be smart about absolute URLs.

Or, to say it another way, I think prefix semantics and resolution semantics need to remain separate options. Trying to have a hybrid approach is problematic in situations like this where the code has to decide whether `reports:batchGet` is absolute or relative. We could try to be fancy and say "`reports` is an unknown protocol, therefor it is a relative URL". But that is too magical for my taste.

Sounds like renaming the option and copying the code from Ky is the way to go here. However, the OP also expects leading slashes to be allowed in the input URL when using `prefixUrl`. Ky currently throws an error when the user does that. We could change that to be more user friendly.

**Comment by rhodgkins** [comment]
Just thought I'd add to my original description (as you keep mentioning what I expect to see) for clarity...

>OP also expects leading slashes to be allowed in the input URL

The only reason the example in my initial description has a leading slash is because that's the last thing I ended up trying. I originally had no leading slash because that does indeed make more sense, and is what I want (ie, stick the `reports:batchGet` on the end of the provided `baseUrl`).
I only changed it to add a leading slash after looking at the [documentation](https://github.com/sindresorhus/got#baseurl) which shows that the leading slash doesn't make a difference - then that's what I ended up pasting into here.


>OP doesn't expect that to completely override the input URL

Yep, this is the main issue from my perspective (I realise I'm only just me, so pinch of salt to what I have to say 😄 ). The confusing thing about this is the way `new URL(url, baseUrl)` changes the protocol of the output. 
I've personally always used that constructor to concatenate the path (`url`) onto the `baseUrl` (except in the case where `url` has a leading slash, then it's replace the path of the base URL), and never until now have I realised what it actually does.
Using `./reports:batchGet` makes sense (to me at least now - even though I have said it isn't ideal in my original comment, its actually correct as it is a relative path to the base URL). 
It's probably not enough for everyone (as we all know not everyone reads the documentation - I'm a prime example here with URL resolution) - but adding more examples to the documentation for `baseUrl` would help too! 

Adding another `prefixUrl` option would be good, but then having an error thrown for a leading slash seems weird, when the current behaviour when using `baseUrl` is to [strip the leading slash](https://github.com/sindresorhus/got/blob/master/source/normalize-arguments.ts#L124) anyway 🙃 (which is why I didn't bother to paste in examples without a slash).


Sorry for a probably useless bit of extra info, but like I said I thought I'd clarify what I was actually expecting to happen, and what made sense when I was using it!
Cheers for the hard work you guys put in 👍
