### ISSUE TITLE
GOT error when testing with nock

### ISSUE THREAD

**Issue by MartMong** [sindresorhus/got#847]
#### Describe the bug

 - Node.js version: 10.16
 - OS & version: MacOS

#### Actual behavior
when I use got test timeout error with nock 
got throw RequestError 

{ RequestError: Nock: No match for request {
  "method": "GET",
  "url": "http://delay.com/",
  "headers": {
    "user-agent": "got/9.6.0 (https://github.com/sindresorhus/got)",
    "accept-encoding": "gzip, deflate"
  }
}

while I use axios doing the same thing It works properly throwing timeoutError 

#### Expected behavior
Should correctly handle to request to nock server and throw an actual timeOut error

#### Code to reproduce

```js
...
const nock = require('nock')
const got = require('got')
const axios = require('axios')

nock('http://delay.com')
  .get('/')
  .delay(10000)
  .reply(200, 'hey');

axios.get('http://delay.com/', {timeout: 1000})
  .then(res => console.log(res))
  .catch(e => {
    console.log(e)
    console.log(e.code)
  })

got.get('http://delay.com/', { timeout: 1000 })
  .then(res => console.log(res))
  .catch(e => {
    console.log(e)
  }
)

```

**Comment by sebz** [comment]
Hey @MartMong I'm facing the same issue. 
You closed this issue without providing any comment. I'm reading my code over and over looking for a mistake but can't find anything... 🙏

**Comment by lbillinghamnds** [comment]
@sebz I _think_ that it might be because `got` defaults to retrying requests.
Since `nock`'s mocks are only good for 1 request, 
when `got` retries the mock has already been consumed and there is no mock on that route.
So `nock` throws a `RequestError`

Details on this nock issue https://github.com/nock/nock/issues/2198 (that I opened ... then realized was not a :bug:)
