### ISSUE TITLE
afterResponse hook not called for stream

### ISSUE THREAD

**Issue by stevenvachon** [sindresorhus/got#871]
#### Describe the bug

 - Node.js version: 12.10.0
 - OS & version: macOS 10.14.6

#### Code to reproduce

```js
import {stream as streamHTTP} from 'got';

streamHTTP(url, {
	hooks: {
		afterResponse: () => console.log('not called')
	},
	//retries: 0
})
.on('error', error => console.error(error))
.on('response', stream => console.log(stream));
```

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
If you want to serve a new response, you should pass custom `request` function: https://github.com/sindresorhus/got#request

**Comment by stevenvachon** [comment]
I was trying to use it to retry a request using "get" because it'd previously responded with a 405 status using "head".

**Comment by szmarczak** [comment]
[Retrying is disabled for streams:](https://github.com/sindresorhus/got#retry)

> Note: When using streams, this option is ignored.

https://github.com/sindresorhus/got/blob/3ff567524072b0d2417802002602df7fd8e21cc6/source/as-stream.ts#L19

This is because the connection may get broken while downloading, and if the retry functionality was here you would get duplicated content. To "retry" properly you need to make your own function that will handle the errors - then make new stream and **pipe it again** (if you were writing to a file, don't forget to clear it).

The point is that Got cannot clear the file you were writing into.

Any suggestions how to fix this problem are welcome :)

**Comment by stevenvachon** [comment]
Thanks!

**Comment by szmarczak** [comment]
I'll leave this issue open for now, we need to document this properly.

**Comment by szmarczak** [comment]
Fixed
