### ISSUE TITLE
`stream.pipeline(...)` ignores Nock's `No match for request` error

### ISSUE THREAD

**Issue by lpinca** [sindresorhus/got#976]
#### Describe the bug

 - Node.js version: v13.3.0
 - OS & version: macOS 10.15.1

[`nock`](https://github.com/nock/nock) emits an error on the request object when a request is made for a given scope and the URL is not present in the interceptor list. The error is swallowed by `got@10.0.2`.

#### Code to reproduce

```js
const got = require('got');
const nock = require('nock'); // nock@11.7.0

nock('https://example.com')
  .get('/?foo=bar')
  .reply(200, {});

got('https://example.com/', {
  method: 'GET',
  responseType: 'json',
  retry: 0
}).catch(console.error);
```

#### Actual behavior

The error is swallowed.

#### Expected behavior

The error is handled and the promise rejected. This is what happens in `got@9.6.0`.

#### Checklist

- [x] I have read the documentation.
- [x] I have tried my code with the latest version of Node.js and Got.

**Comment by szmarczak** [comment]
Unfortunately this is a `nock` issue.

Nock's `request` object emits `finish` just before the `error` event. The `stream.pipeline` callback may be called only once. And that happens when `finish` is emitted. `error` is also caught by `stream.pipeline` but it's ignored since the payload was pushed successfully.

It can be simply fixed on our side though:

```js
request.once('error', error => {
	if (request.writableFinished) {
		emitError(error);
	}
});
```

Please open a `nock` issue about it.

@sindresorhus Should we implement this workaround?

**Comment by sindresorhus** [comment]
@szmarczak Can you open a Nock issue to ensure it will be fixed at some point? And add a link to the issue as a comment where the workaround in Got is.
